# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easycommit < Formula
  desc "A TUI tool for generating AI-powered git commit messages."
  homepage "https://github.com/txperl/easycommit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_darwin_amd64.tar.gz"
      sha256 "9fcd61ddf29051a59774b943643db34301872233262a4cc4f2ce5021b00253a9"

      define_method(:install) do
        bin.install "easycommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_darwin_arm64.tar.gz"
      sha256 "0f5b85c5c37cd21b54e22060cfa333260d0532ccf18afc84a1ac33ddfe359d1f"

      define_method(:install) do
        bin.install "easycommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_linux_amd64.tar.gz"
      sha256 "24d6e1ea6fd1d9607c969e6108c162291ebb82d50902408ff1de43d579a17c59"
      define_method(:install) do
        bin.install "easycommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_linux_arm64.tar.gz"
      sha256 "53500ec4ae68b98b054ad43ed2db23d5628045b687b272ddacf6a63a38f318a9"
      define_method(:install) do
        bin.install "easycommit"
      end
    end
  end
end
