# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easycommit < Formula
  desc "A TUI tool for generating AI-powered git commit messages."
  homepage "https://github.com/txperl/easycommit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_darwin_amd64.tar.gz"
      sha256 "b003327cea22c06701860dfa4fd11d2e1ffaf69fea931262a88d73f8b8dfb636"

      define_method(:install) do
        bin.install "easycommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_darwin_arm64.tar.gz"
      sha256 "77bece64dfc7ea27891726080234f5e8e0ef3facd65c9cf5c9d18f97200a5373"

      define_method(:install) do
        bin.install "easycommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_linux_amd64.tar.gz"
      sha256 "65f66e1196c0109f49dbf813531c1b31b3fecac6a5efb1a6bc9d448724187cea"
      define_method(:install) do
        bin.install "easycommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/easycommit/releases/download/v0.1.0/easycommit_0.1.0_linux_arm64.tar.gz"
      sha256 "05132cd471a122960b65af4f9e20d87b9d9aa876ebb3f2f38ccd7a5b355ab5b4"
      define_method(:install) do
        bin.install "easycommit"
      end
    end
  end
end
