# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipfly < Formula
  desc "A TUI tool for running multiple code snippets, in a single terminal tab."
  homepage "https://github.com/txperl/snipfly"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.3/snipfly_0.1.3_darwin_amd64.tar.gz"
      sha256 "0a00ecab675d5d1c2a601bbebbbad3066c4bdd4a6294a2d3137cda50964c217b"

      define_method(:install) do
        bin.install "snipfly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.3/snipfly_0.1.3_darwin_arm64.tar.gz"
      sha256 "6555a28fabb1743d225d35a01e80222e4fe6ea22503974087c937808b98bf800"

      define_method(:install) do
        bin.install "snipfly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.3/snipfly_0.1.3_linux_amd64.tar.gz"
      sha256 "3cc4d069314972c8704b2b1623a7bda9e27e6c2254465997649e8969a044a4d7"
      define_method(:install) do
        bin.install "snipfly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.3/snipfly_0.1.3_linux_arm64.tar.gz"
      sha256 "157c8f6a093484b1012d2f055488a78a91daaf5d578a0150ea0bec98721e2e63"
      define_method(:install) do
        bin.install "snipfly"
      end
    end
  end
end
