# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipfly < Formula
  desc "A TUI tool for running multiple code snippets, in a single terminal tab."
  homepage "https://github.com/txperl/snipfly"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.2/snipfly_0.1.2_darwin_amd64.tar.gz"
      sha256 "d0849cb6394d87900e52d43a36213df495dae90af532f11af1ea4dbc993ac60f"

      define_method(:install) do
        bin.install "snipfly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.2/snipfly_0.1.2_darwin_arm64.tar.gz"
      sha256 "a936f7f8c768592d2dcef8eaa2aa32089a4f8105b2e9ee1f051a3ce5fcc10c03"

      define_method(:install) do
        bin.install "snipfly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.2/snipfly_0.1.2_linux_amd64.tar.gz"
      sha256 "2f28d37201edaaad5799a595808fdf48d1c7d9755765e541bddd3df1f40fd639"
      define_method(:install) do
        bin.install "snipfly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txperl/snipfly/releases/download/v0.1.2/snipfly_0.1.2_linux_arm64.tar.gz"
      sha256 "1707ff23adac2c5a432f9b65441d6b3ffad5cd456e578e1ea8be6f99912ecb8d"
      define_method(:install) do
        bin.install "snipfly"
      end
    end
  end
end
