# This file was generated by GoReleaser. DO NOT EDIT.
cask "snipfly" do
  name "snipfly"
  desc "A TUI tool for running multiple code snippets, in a single terminal tab."
  homepage "https://github.com/txperl/snipfly"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snipfly"

  on_macos do
    on_intel do
      url "https://github.com/txperl/snipfly/releases/download/v#{version}/snipfly_#{version}_darwin_amd64.tar.gz"
      sha256 "1685be6eb50e9b493a69afef92499a12d055e6614d655242ce3124cd9cdd0788"
    end
    on_arm do
      url "https://github.com/txperl/snipfly/releases/download/v#{version}/snipfly_#{version}_darwin_arm64.tar.gz"
      sha256 "6bd48e1099ea43e00cc5a061c301991bcb8c44908b7b226239ff9cb6c6e3b7fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/txperl/snipfly/releases/download/v#{version}/snipfly_#{version}_linux_amd64.tar.gz"
      sha256 "41d3f40df51cfc73b50a2e7ec73259cc9f5eb763dd8c74b25b10ce4b4e684013"
    end
    on_arm do
      url "https://github.com/txperl/snipfly/releases/download/v#{version}/snipfly_#{version}_linux_arm64.tar.gz"
      sha256 "0a53dc88a834ea953bedde069b5a26ad8567b85bae785d996c0ae38ee4263879"
    end
  end

  # No zap stanza required
end
